project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Computing Technology"
  description: "Computing Technology is an introduction to computer science through a range of programming languages, suitable for those with or without prior programming experience. This module emphasizes problem-solving, focusing on correctness, design, and style. The module demonstrates concepts using various programming languages."
  site-url: "https://SQ4007-2025.github.io/website/"
  favicon: "images/favicon.ico"

  repo-url: https://github.com/SQ4007-2025/website
  repo-actions: [edit, issue]

  open-graph: true

  twitter-card:
    creator: "@EdHarris9000"
    image: "images/twitter-card.png"

  page-footer:
    left: "&copy; 2025 游낽 [W. Edwin Harris](https://weharris.me)"
    center: "游늵 [The Statistics Lab](https://thestatisticslab.com)"
    right: "游 Built with [Quarto](https://quarto.org/)."
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/weharris
        text: "Course GitHub repo"
      - icon: youtube
        href: https://youtube.com/@TheStatisticsLab
        text: "YouTube"
      - icon: discord
        href: https://discord.gg/dnNTE6xhhu
        text: "Join our Discord"

    style: "docked"
    search: true
    collapse-level: 1 
    contents:
      - href: index.qmd
        text: Welcome!
      - href: module-schedule.qmd
        text: Schedule
      - href: module-syllabus.qmd
        text: Syllabus
      - href: module-links.qmd
        text: Useful links
      - href: module-faq.qmd
        text: FAQ
      - section: "Tutorials"
        contents:
          - href: tutorials/tutorial-week-2.qmd
            text: "Week 02 游릭"
          - href: tutorials/tutorial-week-3.qmd
            text: "Week 03 游릭"
          - href: tutorials/tutorial-week-4.qmd
            text: "Week 04 游릭"
          - href: tutorials/tutorial-week-5.qmd
            text: "Week 05 游릭"
          - href: tutorials/tutorial-week-6.qmd
            text: "Week 06 游릭"
          - href: tutorials/tutorial-week-7.qmd
            text: "Week 07 游냀"
          - href: tutorials/tutorial-week-8.qmd
            text: "Week 08 游늵"
          - href: tutorials/tutorial-week-9.qmd
            text: "Week 09 游깷"
          - href: tutorials/tutorial-week-10.qmd
            text: "Week 10 游냀"
          

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual